// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOVle15rENt693CsICQTzLnE4RAzMaaHY',
    appId: '1:530414090463:web:f67cb3ad5be0bb7540516a',
    messagingSenderId: '530414090463',
    projectId: 'coding-assistant-2c00b',
    authDomain: 'coding-assistant-2c00b.firebaseapp.com',
    storageBucket: 'coding-assistant-2c00b.appspot.com',
    measurementId: 'G-5XVRLRS97M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbjjE1yyL7JIBCX6xAZjV9jmgB24UsjcA',
    appId: '1:530414090463:android:5c8ae97df319d42e40516a',
    messagingSenderId: '530414090463',
    projectId: 'coding-assistant-2c00b',
    storageBucket: 'coding-assistant-2c00b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX06hxm7wgaDRRFM19tj20xU9CZ4YQL7g',
    appId: '1:530414090463:ios:6b03277a3461df9c40516a',
    messagingSenderId: '530414090463',
    projectId: 'coding-assistant-2c00b',
    storageBucket: 'coding-assistant-2c00b.appspot.com',
    iosClientId:
        '530414090463-rjdsa8l596dimlbsuju6kp452ahg0il5.apps.googleusercontent.com',
    iosBundleId: 'com.example.codingAssistantFlutter',
  );
}
